### ISSUE TITLE
Evaluation question

### ISSUE THREAD

**Issue by ljylabuqila** [Green-Wood/CoMER#17]
I use checkpoint in lightning_logs/version_0 to evaluate model but it said math tag not found for     these things. 
![mmexport1715734522446](https://github.com/Green-Wood/CoMER/assets/163510808/cac26453-55cf-473b-bded-031c63658315)
Did anyone meet this problem?

**Comment by ljylabuqila** [comment]
The struct rate is too low. Even if I tried to install libxml2, the results keep the same. I use CUDA 11.8, pytorch 2.2.2 and Python 10. Other versions are the same as what the readme says.
![1715765906899](https://github.com/Green-Wood/CoMER/assets/163510808/7a54552f-925d-4d0e-8e40-c1da2680021f)

**Comment by ljylabuqila** [comment]
I have solved this problem by installing libxml.
I use

`sudo apt-get install libxml-libxml-perl`

This can solve it but "sudo apt-get install libxml2-dev" can't.

**Comment by Fyzjym** [comment]
Contribute another solution for the missing “libxml”:
'''
conda install perl-xml-libxml -y
'''
For check, :
'''
perl -MXML::LibXML -e 'print "Installed: $XML::LibXML::VERSION\n";'
'''
